#GitHub Login
spring.security.oauth2.client.registration.github.client-id=Ov23livomo2OgLWOCtJ1
spring.security.oauth2.client.registration.github.client-secret=fb1c4202b2de72e7c8682b21f199e6989d69e338

#Google Login
spring.security.oauth2.client.registration.google.client-id=965097507033-1r4jv5i1mblvl166oefft8c5ggjon11o.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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