spring.application.name=ManArt
spring.datasource.url=jdbc:mysql://127.0.0.1:3306/db_manart
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
jwt.clavesecreta=dGoRh7tlf2+mj3kafEUi9OQvwk8IlmkyuamvV/23ksk=

spring.config.import=classpath:confidential.properties